import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync,readFileSync,writeFileSync,chmodSync,statSync,readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID,generateKeyPairSync,createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { onlineBackup,verifyBackup,restoreBackup,listReservations,cancelReservation } from '../operations.mjs';
import { validateProduction } from '../production.mjs';
import { createLimits } from '../limits.mjs';
import { EventEmitter } from 'node:events';
function database(t){const dir=mkdtempSync(join(tmpdir(),'recorder-ops-'));chmodSync(dir,0o700);const path=join(dir,'live.sqlite'),db=new DatabaseSync(path);chmodSync(path,0o600);db.exec("PRAGMA journal_mode=WAL;CREATE TABLE schema_version(version INTEGER PRIMARY KEY);INSERT INTO schema_version VALUES(2);CREATE TABLE policy_state(id INTEGER PRIMARY KEY,sequence INTEGER,canonical TEXT);INSERT INTO policy_state VALUES(1,42,'{}');CREATE TABLE download_entry_requests(day TEXT,channel TEXT,count INTEGER,PRIMARY KEY(day,channel));INSERT INTO download_entry_requests VALUES('2026-09-15','website',8);CREATE TABLE referral_operations(device TEXT,series TEXT,id TEXT,state TEXT,PRIMARY KEY(device,series,id));CREATE TABLE referral_accounts(device TEXT,series TEXT,used INTEGER);INSERT INTO referral_accounts VALUES('hmac-device','3.2',3);");const op=randomUUID();db.prepare('INSERT INTO referral_operations VALUES(?,?,?,?)').run('hmac-device','3.2',op,'reserved');t.after(()=>{db.close();rmSync(dir,{recursive:true,force:true});});return {dir,path,db,op};}
test('online WAL backup, integrity and non-overwriting restore drill',async t=>{const f=database(t),path=join(f.dir,'backup.sqlite');const result=await onlineBackup(f.path,path);assert.equal(result.state.policySequence,42);assert(!readdirSync(f.dir).some(name=>name.includes('.tmp')));const portable=new DatabaseSync(path,{readOnly:true});assert.equal(portable.prepare('PRAGMA journal_mode').get().journal_mode,'delete');portable.close();assert.equal(result.state.downloadEntries,8);assert.equal(statSync(path).mode&0o777,0o600);assert.equal(statSync(path+'.manifest.json').mode&0o777,0o600);f.db.exec("UPDATE download_entry_requests SET count=9");assert.equal(verifyBackup(path).downloadEntries,8);const restored=join(f.dir,'restored.sqlite');assert.equal(restoreBackup(path,restored).downloadEntries,8);assert.throws(()=>restoreBackup(path,restored),/exists/);await assert.rejects(onlineBackup(f.path,path),/exists/);const db=new DatabaseSync(restored);assert.equal(db.prepare('SELECT state FROM referral_operations').get().state,'reserved');db.close();});
test('corrupted backup cannot restore',async t=>{const f=database(t),backup=join(f.dir,'copy.sqlite');await onlineBackup(f.path,backup);const bytes=readFileSync(backup);bytes[200]^=1;writeFileSync(backup,bytes);assert.throws(()=>restoreBackup(backup,join(f.dir,'reject.sqlite')),/digest/);});
test('administrator explicitly cancels reserved operation with audit and no trial refund',t=>{const f=database(t),rows=listReservations(f.path);assert.equal(rows.length,1);assert(!JSON.stringify(rows).includes('hmac-device'));assert.equal(rows[0].operationID,f.op);assert.throws(()=>cancelReservation(f.path,rows[0].handle,{operator:'operator-1',reason:'confirmed_process_ended',confirmed:false}),/confirmation/);const result=cancelReservation(f.path,rows[0].handle,{operator:'operator-1',reason:'confirmed_process_ended',confirmed:true});assert.equal(result.usedTrialsChanged,false);assert.equal(f.db.prepare('SELECT used FROM referral_accounts').get().used,3);const audit=f.db.prepare('SELECT * FROM referral_admin_audit').get();assert.equal(audit.previous_state,'reserved');assert.equal(audit.next_state,'cancelled');assert.equal(audit.operator,'operator-1');assert.throws(()=>cancelReservation(f.path,rows[0].handle,{operator:'operator-1',reason:'incident_recovery',confirmed:true}),/finalized/);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM referral_admin_audit').get().n,1);});
test('completed operations cannot be refunded by administrator',t=>{const f=database(t),row=listReservations(f.path)[0];f.db.exec("UPDATE referral_operations SET state='completed'");assert.throws(()=>cancelReservation(f.path,row.handle,{operator:'operator-1',reason:'user_confirmed_abandoned',confirmed:true}),/no refund/);assert.equal(f.db.prepare('SELECT state FROM referral_operations').get().state,'completed');});
test('ops CLI runs isolated backup / verify / restore / reservation audit commands',async t=>{const f=database(t),backup=join(f.dir,'cli.sqlite');const run=args=>spawnSync(process.execPath,[new URL('../ops.mjs',import.meta.url).pathname,...args],{env:{...process.env,STATS_DB:f.path},encoding:'utf8'});assert.equal(run(['backup',backup]).status,0);assert.equal(run(['verify-backup',backup]).status,0);assert.equal(run(['restore',backup,join(f.dir,'cli-restored.sqlite')]).status,0);const rows=JSON.parse(run(['reservations']).stdout);assert.equal(run(['cancel-reservation',rows[0].handle,'admin','confirmed_process_ended','--confirm-process-ended']).status,0);assert.equal(run(['cancel-reservation',rows[0].handle,'admin','confirmed_process_ended']).status,1);});
function response(){const r=new EventEmitter();r.writeHead=(code)=>r.status=code;r.end=()=>{};return r;}
test('request/ticket windows and concurrency are bounded and capacity releases exactly once',()=>{let clock=0;const admit=createLimits({MAX_REQUESTS_PER_MINUTE:'4',MAX_TICKETS_PER_MINUTE:'1',MAX_ACTIVE_REQUESTS:'2',MAX_ACTIVE_DOWNLOADS:'1'},{clock:()=>clock});const req={method:'GET'},download=new URL('http://local/r/download?ticket=x'),r=response();assert(admit(req,r,download));assert.equal(admit(req,response(),download),false);r.emit('finish');r.emit('close');const next=response();assert(admit(req,next,download));next.emit('close');const head=response();assert(admit({method:'HEAD'},head,download));head.emit('finish');const blocked=response();assert.equal(admit(req,blocked,download),false);assert.equal(blocked.status,429);clock=60000;const ticket=new URL('http://local/r/abc/ticket'),first=response();assert(admit({method:'POST'},first,ticket));first.emit('finish');assert.equal(admit({method:'POST'},response(),ticket),false);});
test('production permission, package manifest and policy key binding checks fail closed',t=>{const dir=mkdtempSync(join(tmpdir(),'recorder-prod-test-'));chmodSync(dir,0o700);t.after(()=>rmSync(dir,{recursive:true,force:true}));const keys=generateKeyPairSync('ed25519'),zip=Buffer.from('504b030400010203','hex');const env={NODE_ENV:'production',HOST:'127.0.0.1',POLICY_FILE:join(dir,'policy.json'),POLICY_PRIVATE_KEY_FILE:join(dir,'key.pem'),STATS_DB:join(dir,'state.sqlite'),REFERRAL_PUBLIC_ORIGIN:'https://example.com',REFERRAL_DEVICE_PEPPER:'test-only'.repeat(8),REFERRAL_SERIES:'3.2',REFERRAL_ARTIFACT_FILE:join(dir,'artifact.zip'),REFERRAL_ARTIFACT_SHA256:createHash('sha256').update(zip).digest('hex'),RELEASE_ARTIFACT_BUILD:'6',RELEASE_MANIFEST_FILE:join(dir,'manifest.json')};const manifest={schema:1,product:'lossless-system-audio-recorder',version:'3.2.0',build:6,sha256:env.REFERRAL_ARTIFACT_SHA256,bytes:zip.length,bundleID:'app.lowpower.lossless-system-audio-recorder',policyPublicKey:keys.publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('base64'),signingTeamID:'TESTTEAM00',notarizationID:randomUUID()};writeFileSync(env.POLICY_FILE,'{}',{mode:0o600});writeFileSync(env.POLICY_PRIVATE_KEY_FILE,keys.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});writeFileSync(env.REFERRAL_ARTIFACT_FILE,zip,{mode:0o600});const save=()=>writeFileSync(env.RELEASE_MANIFEST_FILE,JSON.stringify(manifest),{mode:0o600});save();assert.doesNotThrow(()=>validateProduction(env));chmodSync(env.POLICY_FILE,0o644);assert.throws(()=>validateProduction(env),/0600/);chmodSync(env.POLICY_FILE,0o600);manifest.build=7;save();assert.throws(()=>validateProduction(env),/manifest mismatch/);manifest.build=6;manifest.policyPublicKey='different';save();assert.throws(()=>validateProduction(env),/public key mismatch/);assert.throws(()=>validateProduction({...env,HOST:'0.0.0.0'}),/loopback/);});

test('scheduled backup and health checks detect missing, old and corrupt snapshots',async t=>{
 const {scheduledBackup,checkHealth}=await import('../maintenance.mjs');const f=database(t),env={STATS_DB:f.path,BACKUP_DIR:f.dir,PORT:'8793'};
 const good={fetchImpl:async()=>({status:200,json:async()=>({status:'ready'})})};
 await assert.rejects(checkHealth(env,good),/missing/);assert.equal((await scheduledBackup(env)).status,'backup_verified');assert.equal((await checkHealth(env,good)).backupVerified,true);
 await assert.rejects(checkHealth(env,{...good,now:Date.now()+37*3600*1000}),/older/);
 await assert.rejects(checkHealth(env,{fetchImpl:async()=>({status:503})}),/not ready/);
});
